INSERT INTO CATEGORIA (ID,NOME,CRIADO,ATUALIZADO) VALUES (NULL,'Livros',NOW(),NULL);
INSERT INTO CATEGORIA (ID,NOME,CRIADO,ATUALIZADO) VALUES (NULL,'Eletrônicos',NOW(),NULL);
INSERT INTO CATEGORIA (ID,NOME,CRIADO,ATUALIZADO) VALUES (NULL,'Computadores',NOW(),NULL);